### ISSUE TITLE
Share the specs file in the mingwpy github repo

### ISSUE THREAD

**Issue by ogrisel** [mingwpy/mingwpy#8]
To validate phase 1 we need to share working specs files so that it's possible to combine them manually with a mingwpy toolchain built with the mingwpy-dev branch of the mingw-builds repo.

For now we can just put them in the root folder of this repo.

The script to automate the assembly of the toolchain with the correct specs file into distributable packages (wheels and zip files) is scheduled for phase 2.

**Comment by carlkl** [comment]
@ogrisel, I will add these parts today in the evening or tomorrow.

**Comment by carlkl** [comment]
the specs files for 32|64 bit msvcr90|100 runtimes are now added:
https://github.com/mingwpy/mingw-builds/commit/c608e74f9a899c2505e188e4c5a257b3524b1bcd

**Comment by techtonik** [comment]
Some intro about what these files do would be nice as well.

**Comment by ogrisel** [comment]
I would rather like to have them in the mingwpy repo instead of the mingw-builds repo. I think we should try to make it such as mingw-builds is as generic as possible so that changes can be contributed upstream without anything specific related to Python and mingwpy.

**Comment by carlkl** [comment]
I added the specs manually add this step to fullfill _phase1_. 
Later on (_phase2_) these specs has to be created in a step after building the toolchain with the help of an additionally script within mingw-builds. Thus the _standalone_ toolchain archives will have these specs included automatically. The wheel builder will then use these archives to build wheels specific to the python version.

**Comment by anthrotype** [comment]
Hello, and thank you for working on this great project!

First of all, sorry if my question might sound stupid (I'm not familiar with compiling compilers...).

I noticed one difference (among several others) between the specs files from the latest mingwpy release (from August 2015) and the latest ones from commit https://github.com/mingwpy/mingw-builds/commit/c608e74f9a899c2505e188e4c5a257b3524b1bcd

``` diff
--- /c/Python27/share/mingwpy_4.9.2/lib/gcc/i686-w64-mingw32/4.9.2/specs
+++ /c/Python27/share/mingwpy_5.3.0/lib/gcc/i686-w64-mingw32/5.3.0/specs
@@ -52,53 +52,53 @@
*link_gcc_c_sequence:
-%G %L %G %{shared|mdll: msvcr90.dll.res%s} %{!shared: %{!mdll: msvcr90.exe.res%s}}
+%G %L %G
```

I wonder, was this change intentional, and what does this imply?

The reason I ask is that I've tried to use these new specs files with the precompiled toolchain available at https://bitbucket.org/carlkl/mingw-w64-for-python/downloads/i686-5.3.0-static-release-win32-sjlj-rt_v4-rev201602.7z (uploaded by @carlkl one week ago). I also placed copies of libpython27.dll.a and libmsvcr90.a inside the C:\Python27\libs folder.

However, I encounter an runtime error whenever I try to run executables generated with this gcc version --- even very simple ones, such as the conftest.exe generated by autoconf `configure` scripts. The gcc command returns successfully with 0 exit code, however when I run the executable, Windows throws an Visual C++ Runtime Error [R6034](https://msdn.microsoft.com/en-us/library/ms235560%28v=vs.90%29.aspx).
The docs suggest that the executable might be missing the required manifest.

Now, if I try to modify the specs file to also link with the above msvcr90 resource files, and also if I copy  `msvcr90.exe.res` and `msvcr90.dll.res` found inside `mingwpy\i686-w64-mingw32\lib` folder, then the above error message disappears and executables can be run.

So the question is, how important are these two  `msvcr90.exe.res` and `msvcr90.dll.res` files? Will they be packaged in the mingwpy wheel builder? Should the 5.3.0 specs link to these files, like the one from mingwpy 4.9.2 does?

Thank you in advance.

Cosimo

**Comment by carlkl** [comment]
@anthrotype, that's very well observed. The manifest objects has to be supplied as well, especially for VS 2010 compatibility (msvcr90).

My observation until now was, that only under certain circumstances (py2exe, running as service) the existance of manifest matters for VS 2010. I wonder why this is relevant for such simple usecases you described. Is this tested on Windows10?

**Comment by anthrotype** [comment]
I haven't tried with Windows 10, but I may give it a go.
I was only testing it in Windows 7.

I also noticed that this runtime error R6034 only occurs when an instance of `msvcr90.dll` appears in the %PATH%. In fact, because I installed a copy of Python 2.7 as single user, the msvcr90.dll was placed by the installer next to the python executable, which happens to be in my PATH as well.

If I remove this directory from the PATH and try to run a gcc-made msvcr90-linked executable, then Windows simply complains that it cannot find the msvcr90.dll.

It's worth noting that the msvcr90.dll _is_ actually installed system-wide somewhere inside C:\Windows\WinSxS, through the official "Microsoft Visual C++ 2008 SP1 Redistributable Package (x86)" -- which I believe is the same `vcredist_x86.exe` package which gets installed by the Python installer when one selects "for all users".

**Comment by anthrotype** [comment]
OK, I recompiled the toolchain under Windows 10, and can confirm that the latter also raises Runtime Error R6034, just like with Windows 7. The error appears when:
- a copy of msvcr90.dll is in the %PATH% (e.g. inside C:\Python27 when installing as single-user);
- the gcc-compiled executable is linked to the msvcr90.dll via @carlkl's "specs" file (https://github.com/mingwpy/mingw-builds/commit/c608e74f9a899c2505e188e4c5a257b3524b1bcd)

If msvcr90.dll is not in the %PATH% or next to the .exe, then Windows will complain that the msvcr90.dll is missing, even though it is installed system-wide in C:\Windows\WinSxS.

The fix is to modify the custom gcc "specs" to reference the *.res manifest files for msvcr90. After that, the generated executables run just fine.

**Comment by anthrotype** [comment]
a simple snippet like this is enough to trigger the issue:

``` c
#include <stdio.h>
int main () {
  FILE *f = fopen ("test.out", "w");
  return ferror(f) || fclose(f) != 0;
}
```

After compiling `gcc -o test.exe test.c`, the generated `./test.exe` will either complain msvcr90.dll is missing, or will raise runtime error R6034 if the dll appears in the %PATH%.

**Comment by carlkl** [comment]
no panic,

I rework that and put it on the mingwpy repo later this evening.

**Comment by carlkl** [comment]
The latest commit adds all specs and resource files for all variants into the repo. Please test.

**Comment by ogrisel** [comment]
Thanks, will do.

**Comment by carlkl** [comment]
the next step (phase2) is to add this step to mingw-builds as this should be performed automatically.

**Comment by anthrotype** [comment]
sorry to bother again, but the specs files just uploaded by @carlkl with commit 42acc10c2e7cbb1db197d84a5130ecbe7dae010c still do not mention the msvcr90.dll.res and msvcr90.exe.res files.

At line 44: https://github.com/mingwpy/mingwpy/blob/42acc10c2e7cbb1db197d84a5130ecbe7dae010c/specs/msvcr100/i386/lib/gcc/i686-w64-mingw32/5.3.0/specs#L44

shouldn't it read like this?

``` diff
*link_gcc_c_sequence:
-%G %L %G
+%G %L %G %{shared|mdll: msvcr90.dll.res%s} %{!shared: %{!mdll: msvcr90.exe.res%s}}
```

Without that change, I am still getting R6034 runtime error (or msvcr90.dll missing).

**Comment by carlkl** [comment]
:rage: wrong commit. I will correct asap. @anthrotype, you can test this with nevertheless with the link_gcc_c_sequence patched locally.

**Comment by anthrotype** [comment]
sure, no problem!

**Comment by carlkl** [comment]
phew, back at development. the last commit should work now. I got working scipy wheels now!

**Comment by ogrisel** [comment]
I could build the toolchain, cython (for 64 bit Python 3.4 with the right specs) and the mingwpy-dev branch of OpenBLAS. Everything looks good (although I did not test the other combinations of architecture / Python versions).

@anthrotype if you confirm that the 32 bit specs file is now fixed in master, I think we can close this issue.

**Comment by carlkl** [comment]
@ogrisel, great to hear.

**Comment by ogrisel** [comment]
I built a 32 bit toolchain with the specs for Python 2.7 and built openblas and cython with it. Everything is fine. Closing this. @anthrotype feel free to open a new issue if you face any more problems when running your own checks.

**Comment by anthrotype** [comment]
:+1:

**Comment by carlkl** [comment]
I have deserved a :coffee: now
